import {
  ArrowLeftRight,
  CloudRain,
  Droplets,
  Flame,
  Footprints,
  Gem,
  Landmark,
  type LucideIcon,
  Mountain,
  Route,
  Skull,
  Snowflake,
  Sparkles,
  Sun,
  Thermometer,
  TreePalm,
  TreePine,
  TrendingUp,
  Triangle,
  Waves,
  Wheat,
  Wind,
} from 'lucide-react';
import type { Biome, ClimateType, TerrainType } from '../../types';

export const biomeIcons: Record<Biome, LucideIcon> = {
  FOREST: TreePine,
  PLAINS: Wheat,
  MOUNTAIN: Mountain,
  COASTAL: Waves,
  SWAMP: Droplets,
  RUINS: Landmark,
  DESERT: Sun,
  TUNDRA: Snowflake,
  OCEAN: Waves,
};

export const terrainIcons: Record<TerrainType, LucideIcon> = {
  FOREST: TreePine,
  BIRCH_FOREST: TreePine,
  RAINFOREST: TreePine,
  FOREST_EDGE: TreePine,
  SACRED_GROVE: TreePine,
  PLAINS: Wheat,
  MEADOW: Wheat,
  HILLS: TrendingUp,
  FOOTHILLS: TrendingUp,
  DESERT: Sun,
  SALT_FLATS: Sun,
  ICE_TUNDRA: Snowflake,
  GLACIER: Snowflake,
  VOLCANIC: Flame,
  COASTAL: Waves,
  OCEAN: Waves,
  SHORELINE: Waves,
  RIVER_DELTA: Droplets,
  WETLANDS: Droplets,
  SWAMP: Droplets,
  MOUNTAIN: Mountain,
  ALPINE: Mountain,
  CLIFFSIDE: Mountain,
  CANYON: Triangle,
  ANCIENT_RUINS: Landmark,
  CURSED_LAND: Skull,
  BLIGHTED: Skull,
  CRYSTAL_CAVES: Gem,
  DIRT_PATH: Footprints,
  GRAVEL_ROAD: Footprints,
  WOODEN_BRIDGE: ArrowLeftRight,
  STONE_BRIDGE: ArrowLeftRight,
  TRADE_ROUTE: Route,
};

export const climateIcons: Record<ClimateType, LucideIcon> = {
  ARCTIC: Snowflake,
  SUBARCTIC: Snowflake,
  HIGHLAND: Mountain,
  OCEANIC: CloudRain,
  MONSOON: CloudRain,
  CONTINENTAL: Thermometer,
  MEDITERRANEAN: Sun,
  SUBTROPICAL: Sun,
  TROPICAL: TreePalm,
  SEMI_ARID: Wind,
  ARID: Wind,
  VOLCANIC: Flame,
  MAGICAL: Sparkles,
};
